name: Build html and docx documentation
on: [workflow_dispatch]
jobs:
  build:
    name: Build html and docx documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: master
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-page
          path: gh-page
      - name: Checkout modeller
        uses: actions/checkout@v3
        with:
          repository: dasch124/modeller
          path: modeller
      - name: Get python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: "pipenv"
      - name: install graphviz
        run: |
          sudo apt-get install graphviz 
      - name: Build
        run: |
          cd modeller
          python --version
          python -m pip install pipenv
          pipenv install
          pipenv run python modeller.py -d -a generateDocs -i ../master/model.xml
          cp model.docx ../gh-page/
          cp model.html ../gh-page/index.html
          cd ..
      
      - name: Commit results to gh pages
        run: |
          cd gh-page
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.html
          git commit -m "New version of datamodel" -a || true
      - name: Push changes back to GitHub
        uses: ad-m/github-push-action@master
        with:
          branch: gh-page
          directory: gh-page
